language: objective-c
osx_image: xcode7.3
cache: bundler
rvm:
  - 2.3.0

before_install:
  - brew update
  - brew install elixir android-sdk node
  - export ANDROID_HOME=/usr/local/opt/android-sdk
  - gem install bundler -v 1.12.5
  - bundle install
  - curl -o- -L https://yarnpkg.com/install.sh | bash

script:
  - bundle exec ruby main.rb
